[package]
name = "jira"
version = "0.1.0"
edition = "2021"
authors = ["Steffen Baarsgaard <sbaarsgaard@gmail.com>"]

[dependencies]
base64 = "0.21.2"
regex = { version = "1.8.4", features = ["std"], default-features = false }
reqwest = { version = "0.11.20", default-features = false, features = ["json", "rustls-tls", "rustls-native-certs", "rustls-tls-native-roots"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
thiserror = "1.0.56"

[features]
default = []
cloud = []
server = []
