[package]
name = "jira-issue-api"
description = "Personal library for interfacing with Jira issues"
version = "0.2.1"
edition = "2021"
authors = ["Steffen Baarsgaard <sbaarsgaard@gmail.com>"]
repository = "https://github.com/baarsgaard/jira-issue-api"
license-file = "./LICENSE"

[dependencies]
base64 = "0.21"
regex = { version = "1.8", features = ["std"], default-features = false }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "rustls-native-certs", "rustls-tls-native-roots"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[features]
default = []
cloud = []
server = []
